status_code = {
    "2xx": {
        200: "OK",
        201: "Created",
        202: "Accepted",
        203: "Non-Authoritative Information",
        204: "No Content",
        206: "Partial Content",
    },
    "3xx": {
        300: "Multiple Choices",
        304: "Not Modified",
        308: "Permanent Redirect",
    },
    "4xx": {
        400: "Bad Request",
        401: "Unauthorized",
        402: "Payment Required",
        403: "Forbidden",
        404: "Not Found",
        405: "Method Not Allowed",
        406: "Not Acceptable",
        413: "Payload Too Large",
        414: "URI Too Long",
    },
    "5xx": {
        500: "Internal Server Error",
        501: "Not Implemented",
        502: "Bad Gateway",
        503: "Service Unavailable",
        504: "Gateway Timeout",
        505: "HTTP Version Not Supported",
        511: "Network Authentication Required",
    },
}
